"""
CyberSentinel — Pre-built task scenarios.

Three difficulty-graded tasks with alerts, intel reports, and ground-truth labels.
"""

from models import Alert, AlertType, Classification, Severity, ThreatIntelReport


def _easy_task() -> dict:
    """Routine Shift: 5 alerts, 2 false positives, clear signals."""
    alerts = [
        Alert(
            id="ALERT-E001",
            timestamp="2026-04-08T08:12:33Z",
            source_ip="203.0.113.45",
            dest_ip="10.0.1.20",
            alert_type=AlertType.IDS,
            severity_raw=Severity.HIGH,
            description="Signature match: known Cobalt Strike beacon C2 callback pattern detected on port 443.",
            raw_log="[IDS] 203.0.113.45:49321 -> 10.0.1.20:443 | TLS JA3=abc123 | payload sig=CS_BEACON_v4 | bytes=1024",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["203.0.113.45", "CS_BEACON_v4", "JA3=abc123"],
        ),
        Alert(
            id="ALERT-E002",
            timestamp="2026-04-08T08:14:01Z",
            source_ip="10.0.2.15",
            dest_ip="8.8.8.8",
            alert_type=AlertType.DNS,
            severity_raw=Severity.LOW,
            description="DNS query to public resolver 8.8.8.8 from internal workstation.",
            raw_log="[DNS] 10.0.2.15 -> 8.8.8.8 | query=www.google.com | type=A | response=142.250.185.4",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-E003",
            timestamp="2026-04-08T08:15:22Z",
            source_ip="198.51.100.77",
            dest_ip="10.0.1.50",
            alert_type=AlertType.EMAIL,
            severity_raw=Severity.HIGH,
            description="Phishing email detected with malicious attachment (invoice.pdf.exe) from spoofed sender.",
            raw_log="[EMAIL] from=ceo@company-update.biz to=finance@corp.local | subj='Urgent Invoice' | attach=invoice.pdf.exe | SPF=fail DKIM=fail",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=4,
            relevant_iocs=["company-update.biz", "invoice.pdf.exe", "198.51.100.77"],
        ),
        Alert(
            id="ALERT-E004",
            timestamp="2026-04-08T08:17:45Z",
            source_ip="10.0.3.100",
            dest_ip="10.0.3.1",
            alert_type=AlertType.FIREWALL,
            severity_raw=Severity.MEDIUM,
            description="Firewall blocked outbound connection attempt from printer to gateway on unusual port.",
            raw_log="[FW] BLOCK 10.0.3.100:61234 -> 10.0.3.1:8443 | proto=TCP | rule=DEFAULT_DENY | device=HP_LaserJet",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-E005",
            timestamp="2026-04-08T08:19:10Z",
            source_ip="10.0.1.20",
            dest_ip="192.0.2.99",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.CRITICAL,
            description="PowerShell executing encoded command with network callback to external IP on compromised host.",
            raw_log="[EDR] host=WS-FINANCE-01 | proc=powershell.exe | cmd='powershell -enc UwB0AGEAcg...' | parent=winword.exe | net=192.0.2.99:4444",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["192.0.2.99", "powershell -enc", "winword.exe→powershell"],
        ),
    ]

    intel_reports = [
        ThreatIntelReport(
            id="INTEL-E001",
            source="CISA Advisory",
            title="Cobalt Strike Beacon Activity Targeting Financial Sector",
            summary="CISA has observed increased Cobalt Strike beacon activity targeting financial institutions. C2 infrastructure uses TLS with JA3 fingerprint abc123. Source IPs include 203.0.113.0/24 range.",
            iocs=["203.0.113.45", "JA3=abc123", "CS_BEACON_v4"],
            is_disinformation=False,
        ),
        ThreatIntelReport(
            id="INTEL-E002",
            source="Internal SOC",
            title="Known Printer Firmware Update Behavior",
            summary="HP LaserJet printers on subnet 10.0.3.0/24 periodically attempt outbound connections to gateway port 8443 during firmware update checks. This is expected behavior.",
            iocs=[],
            is_disinformation=False,
        ),
    ]

    return {
        "task_id": "easy",
        "name": "Routine Shift",
        "difficulty": "easy",
        "description": "A calm morning shift. Five alerts with clear signals—two are obvious false positives. Intel reports are straightforward and trustworthy.",
        "alerts": alerts,
        "intel_reports": intel_reports,
        "max_steps": 10,
    }


def _medium_task() -> dict:
    """Busy Day: 10 alerts, 4 false positives, subtler signals."""
    alerts = [
        Alert(
            id="ALERT-M001",
            timestamp="2026-04-08T10:02:11Z",
            source_ip="185.220.101.33",
            dest_ip="10.0.1.10",
            alert_type=AlertType.IDS,
            severity_raw=Severity.HIGH,
            description="SQL injection attempt detected in HTTP POST request to web application from Tor exit node.",
            raw_log="[IDS] 185.220.101.33:55012 -> 10.0.1.10:80 | POST /api/login | payload=' OR 1=1-- | UA=Mozilla/5.0 | Tor_exit=true",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=4,
            relevant_iocs=["185.220.101.33", "SQL injection", "Tor exit"],
        ),
        Alert(
            id="ALERT-M002",
            timestamp="2026-04-08T10:05:30Z",
            source_ip="10.0.4.22",
            dest_ip="10.0.4.1",
            alert_type=AlertType.FIREWALL,
            severity_raw=Severity.LOW,
            description="Internal host attempted to access file share on a different VLAN during business hours.",
            raw_log="[FW] ALLOW 10.0.4.22:49876 -> 10.0.4.1:445 | proto=SMB | user=jsmith | share=\\\\fileserv\\shared",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-M003",
            timestamp="2026-04-08T10:08:44Z",
            source_ip="10.0.1.10",
            dest_ip="45.33.32.156",
            alert_type=AlertType.DNS,
            severity_raw=Severity.MEDIUM,
            description="DNS query for domain with high entropy name suggestive of DGA activity from web server.",
            raw_log="[DNS] 10.0.1.10 -> 10.0.0.53 | query=xk7r9m2q4p.click | type=A | response=45.33.32.156 | entropy=4.7",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=4,
            relevant_iocs=["xk7r9m2q4p.click", "DGA", "45.33.32.156"],
        ),
        Alert(
            id="ALERT-M004",
            timestamp="2026-04-08T10:12:05Z",
            source_ip="10.0.2.30",
            dest_ip="13.107.42.14",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.LOW,
            description="Microsoft Teams process connecting to Microsoft cloud infrastructure.",
            raw_log="[EDR] host=WS-HR-05 | proc=Teams.exe | net=13.107.42.14:443 | cert=*.teams.microsoft.com | signed=Microsoft",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-M005",
            timestamp="2026-04-08T10:15:22Z",
            source_ip="91.219.236.18",
            dest_ip="10.0.1.10",
            alert_type=AlertType.IDS,
            severity_raw=Severity.HIGH,
            description="Repeated authentication failures from external IP followed by successful login — potential brute force.",
            raw_log="[IDS] 91.219.236.18 -> 10.0.1.10:22 | SSH auth_fail x47 in 120s then auth_success | user=admin | geo=RU",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["91.219.236.18", "brute force SSH", "47 failures"],
        ),
        Alert(
            id="ALERT-M006",
            timestamp="2026-04-08T10:18:00Z",
            source_ip="10.0.5.10",
            dest_ip="10.0.5.11",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.MEDIUM,
            description="Scheduled task created by IT admin using Group Policy to push software update.",
            raw_log="[EDR] host=DC-01 | proc=schtasks.exe | cmd='schtasks /create /tn UpdatePush /tr c:\\updates\\deploy.bat' | user=CORP\\itadmin | GPO=true",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-M007",
            timestamp="2026-04-08T10:21:33Z",
            source_ip="10.0.1.10",
            dest_ip="198.51.100.200",
            alert_type=AlertType.FIREWALL,
            severity_raw=Severity.HIGH,
            description="Large outbound data transfer from web server to external IP not in allowlist — potential exfiltration.",
            raw_log="[FW] ALLOW 10.0.1.10:50123 -> 198.51.100.200:443 | proto=TLS | bytes_out=54MB in 180s | not_in_allowlist",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["198.51.100.200", "54MB exfiltration", "data exfil"],
        ),
        Alert(
            id="ALERT-M008",
            timestamp="2026-04-08T10:24:10Z",
            source_ip="172.16.0.5",
            dest_ip="172.16.0.1",
            alert_type=AlertType.DNS,
            severity_raw=Severity.LOW,
            description="Internal DNS resolution for Active Directory domain controller.",
            raw_log="[DNS] 172.16.0.5 -> 172.16.0.1 | query=dc01.corp.local | type=A | response=172.16.0.1 | internal",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-M009",
            timestamp="2026-04-08T10:27:55Z",
            source_ip="10.0.1.10",
            dest_ip="10.0.1.11",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.MEDIUM,
            description="Lateral movement detected — compromised web server using PsExec to access adjacent host.",
            raw_log="[EDR] host=WEB-01 | proc=psexec.exe | target=10.0.1.11 | cmd='cmd /c whoami & net user' | user=LOCAL_ADMIN",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["psexec.exe", "lateral movement", "LOCAL_ADMIN"],
        ),
        Alert(
            id="ALERT-M010",
            timestamp="2026-04-08T10:30:11Z",
            source_ip="10.0.6.50",
            dest_ip="10.0.6.51",
            alert_type=AlertType.EMAIL,
            severity_raw=Severity.MEDIUM,
            description="Internal email with macro-enabled document detected by email gateway — but sender is known IT distribution list.",
            raw_log="[EMAIL] from=it-updates@corp.local to=all-staff@corp.local | subj='Q2 Policy Update' | attach=policy.xlsm | SPF=pass DKIM=pass | internal",
            ground_truth_classification=Classification.NEEDS_ESCALATION,
            ground_truth_priority=3,
            relevant_iocs=["policy.xlsm", "macro-enabled"],
        ),
    ]

    intel_reports = [
        ThreatIntelReport(
            id="INTEL-M001",
            source="CrowdStrike Threat Feed",
            title="Tor-Based SQL Injection Campaign Targeting Web Apps",
            summary="An active campaign uses Tor exit nodes to launch automated SQL injection attacks against public-facing web applications. Common source IPs in the 185.220.101.0/24 range.",
            iocs=["185.220.101.33", "SQL injection", "Tor exit node"],
            is_disinformation=False,
        ),
        ThreatIntelReport(
            id="INTEL-M002",
            source="Mandiant Intelligence",
            title="APT29 Lateral Movement Playbook Update",
            summary="APT29 continues to use PsExec and WMI for lateral movement post-compromise. Look for LOCAL_ADMIN account usage and sequential reconnaissance commands (whoami, net user).",
            iocs=["psexec.exe", "lateral movement", "whoami", "net user"],
            is_disinformation=False,
        ),
        ThreatIntelReport(
            id="INTEL-M003",
            source="Recorded Future",
            title="DGA Domains Associated with BotNet Infrastructure",
            summary="New DGA family generating .click TLD domains with high character entropy (>4.5). Associated with data theft botnet. Known C2 IP: 45.33.32.156.",
            iocs=["xk7r9m2q4p.click", "45.33.32.156", "DGA", ".click TLD"],
            is_disinformation=False,
        ),
        ThreatIntelReport(
            id="INTEL-M004",
            source="Internal SOC Playbook",
            title="Brute Force Detection and Response Procedures",
            summary="SSH brute force threshold: >20 failed attempts in 5 minutes from a single IP. If followed by successful login, treat as confirmed compromise. Immediate response: isolate host, rotate credentials.",
            iocs=["SSH brute force", "auth_fail threshold"],
            is_disinformation=False,
        ),
    ]

    return {
        "task_id": "medium",
        "name": "Busy Day",
        "difficulty": "medium",
        "description": "A hectic afternoon shift. Ten alerts with subtler signals — four false positives mixed with correlated attack patterns. Intel is trustworthy but you need to connect the dots across multiple alerts.",
        "alerts": alerts,
        "intel_reports": intel_reports,
        "max_steps": 15,
    }


def _hard_task() -> dict:
    """APT Campaign: 15 alerts, 5 FP, adversarial disinformation in intel."""
    alerts = [
        Alert(
            id="ALERT-H001",
            timestamp="2026-04-08T14:01:22Z",
            source_ip="103.224.182.5",
            dest_ip="10.0.1.100",
            alert_type=AlertType.EMAIL,
            severity_raw=Severity.HIGH,
            description="Spearphishing email with zero-day PDF exploit targeting executive. Sender impersonates board member.",
            raw_log="[EMAIL] from=j.williams@boardmember-advisory.com to=ceo@corp.local | subj='Board Meeting Materials - Confidential' | attach=agenda.pdf | SPF=pass(spoofed) DKIM=fail | x-mailer=custom",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["boardmember-advisory.com", "agenda.pdf", "103.224.182.5", "zero-day PDF"],
        ),
        Alert(
            id="ALERT-H002",
            timestamp="2026-04-08T14:03:10Z",
            source_ip="10.0.1.100",
            dest_ip="103.224.182.5",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.MEDIUM,
            description="Adobe Reader spawned subprocess connecting to external IP after opening PDF attachment.",
            raw_log="[EDR] host=EXEC-01 | proc=AcroRd32.exe | child=rundll32.exe | cmd='rundll32 c:\\users\\ceo\\appdata\\local\\temp\\msupdate.dll,DllMain' | net=103.224.182.5:8080",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["msupdate.dll", "AcroRd32.exe→rundll32.exe", "103.224.182.5"],
        ),
        Alert(
            id="ALERT-H003",
            timestamp="2026-04-08T14:05:45Z",
            source_ip="10.0.2.50",
            dest_ip="10.0.2.1",
            alert_type=AlertType.DNS,
            severity_raw=Severity.LOW,
            description="Standard NTP synchronization query from workstation to internal time server.",
            raw_log="[DNS] 10.0.2.50 -> 10.0.2.1 | query=ntp.corp.local | type=A | response=10.0.2.1 | routine",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-H004",
            timestamp="2026-04-08T14:08:30Z",
            source_ip="10.0.1.100",
            dest_ip="10.0.1.101",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.HIGH,
            description="Credential dumping tool detected — Mimikatz signatures in memory on executive workstation.",
            raw_log="[EDR] host=EXEC-01 | proc=rundll32.exe | memory_sig=MIMIKATZ_v2.2 | lsass_access=true | tokens_extracted=12 | user=SYSTEM",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["MIMIKATZ_v2.2", "lsass_access", "credential dumping"],
        ),
        Alert(
            id="ALERT-H005",
            timestamp="2026-04-08T14:10:15Z",
            source_ip="10.0.3.10",
            dest_ip="10.0.3.11",
            alert_type=AlertType.FIREWALL,
            severity_raw=Severity.LOW,
            description="Printer SNMP discovery broadcast on local subnet — normal network behavior.",
            raw_log="[FW] ALLOW 10.0.3.10:161 -> 10.0.3.255:161 | proto=UDP/SNMP | device=Xerox_Copier | broadcast",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-H006",
            timestamp="2026-04-08T14:13:00Z",
            source_ip="10.0.1.100",
            dest_ip="10.0.1.200",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.HIGH,
            description="WMI lateral movement from compromised executive workstation to domain controller.",
            raw_log="[EDR] host=EXEC-01 | proc=wmic.exe | cmd='wmic /node:10.0.1.200 process call create cmd.exe' | target=DC-MAIN | user=CORP\\admin_svc",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["wmic.exe", "lateral movement", "DC-MAIN", "admin_svc"],
        ),
        Alert(
            id="ALERT-H007",
            timestamp="2026-04-08T14:15:33Z",
            source_ip="10.0.1.200",
            dest_ip="10.0.1.201",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.CRITICAL,
            description="Domain controller: ntdsutil used to create snapshot of Active Directory database — potential credential extraction.",
            raw_log="[EDR] host=DC-MAIN | proc=ntdsutil.exe | cmd='ntdsutil \"activate instance ntds\" ifm \"create full c:\\temp\\ad_backup\"' | user=CORP\\admin_svc",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["ntdsutil.exe", "AD database extraction", "ifm create full"],
        ),
        Alert(
            id="ALERT-H008",
            timestamp="2026-04-08T14:17:20Z",
            source_ip="10.0.4.15",
            dest_ip="10.0.4.1",
            alert_type=AlertType.FIREWALL,
            severity_raw=Severity.MEDIUM,
            description="Developer workstation connecting to internal GitLab instance on standard port during work hours.",
            raw_log="[FW] ALLOW 10.0.4.15:52341 -> 10.0.4.1:443 | proto=HTTPS | host=gitlab.corp.local | user=dev_team | cert=valid",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-H009",
            timestamp="2026-04-08T14:20:05Z",
            source_ip="10.0.1.200",
            dest_ip="198.51.100.55",
            alert_type=AlertType.DNS,
            severity_raw=Severity.HIGH,
            description="Domain controller making DNS-over-HTTPS queries to unknown external resolver — possible DNS tunneling for data exfiltration.",
            raw_log="[DNS] 10.0.1.200 -> 198.51.100.55:443 | DoH detected | query_count=347 in 60s | avg_query_len=189 chars | entropy=5.2 | encoded_data_suspected",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["DNS tunneling", "198.51.100.55", "DoH exfiltration", "high entropy queries"],
        ),
        Alert(
            id="ALERT-H010",
            timestamp="2026-04-08T14:22:40Z",
            source_ip="10.0.5.25",
            dest_ip="10.0.5.1",
            alert_type=AlertType.EMAIL,
            severity_raw=Severity.LOW,
            description="Automated newsletter from marketing platform delivered to employee — no malicious indicators.",
            raw_log="[EMAIL] from=newsletter@mailchimp.com to=marketing@corp.local | subj='Weekly Industry Digest' | no_attach | SPF=pass DKIM=pass | category=bulk",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-H011",
            timestamp="2026-04-08T14:25:18Z",
            source_ip="10.0.1.200",
            dest_ip="10.0.1.202",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.HIGH,
            description="Domain admin account creating new service account and adding to Domain Admins group — persistence mechanism.",
            raw_log="[EDR] host=DC-MAIN | proc=net.exe | cmd='net user svc_backup P@ssw0rd! /add && net group \"Domain Admins\" svc_backup /add' | user=CORP\\admin_svc",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["svc_backup", "Domain Admins", "persistence", "new account creation"],
        ),
        Alert(
            id="ALERT-H012",
            timestamp="2026-04-08T14:28:00Z",
            source_ip="10.0.6.10",
            dest_ip="10.0.6.11",
            alert_type=AlertType.IDS,
            severity_raw=Severity.MEDIUM,
            description="Vulnerability scanner traffic detected from security team's Nessus instance — scheduled scan.",
            raw_log="[IDS] 10.0.6.10 -> 10.0.6.0/24 | scan_type=SYN | ports=1-65535 | tool=Nessus | schedule=weekly_wednesday | user=secops",
            ground_truth_classification=Classification.FALSE_POSITIVE,
            ground_truth_priority=1,
            relevant_iocs=[],
        ),
        Alert(
            id="ALERT-H013",
            timestamp="2026-04-08T14:30:45Z",
            source_ip="10.0.1.200",
            dest_ip="103.224.182.10",
            alert_type=AlertType.FIREWALL,
            severity_raw=Severity.CRITICAL,
            description="Domain controller attempting to upload 2.3 GB archive to external server via HTTPS — likely staged data exfiltration.",
            raw_log="[FW] ALLOW 10.0.1.200:60123 -> 103.224.182.10:443 | proto=TLS | bytes_out=2.3GB | duration=420s | file=ad_backup.7z | not_in_allowlist",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["103.224.182.10", "ad_backup.7z", "2.3GB exfiltration"],
        ),
        Alert(
            id="ALERT-H014",
            timestamp="2026-04-08T14:33:15Z",
            source_ip="10.0.1.200",
            dest_ip="10.0.1.100",
            alert_type=AlertType.ENDPOINT,
            severity_raw=Severity.HIGH,
            description="Anti-forensics: event log clearing detected on domain controller. Attacker covering tracks.",
            raw_log="[EDR] host=DC-MAIN | proc=wevtutil.exe | cmd='wevtutil cl Security && wevtutil cl System' | user=CORP\\svc_backup | event_id=1102",
            ground_truth_classification=Classification.TRUE_POSITIVE,
            ground_truth_priority=5,
            relevant_iocs=["wevtutil.exe", "log clearing", "anti-forensics", "event_id=1102"],
        ),
        Alert(
            id="ALERT-H015",
            timestamp="2026-04-08T14:35:50Z",
            source_ip="10.0.1.100",
            dest_ip="103.224.182.5",
            alert_type=AlertType.IDS,
            severity_raw=Severity.MEDIUM,
            description="Encrypted C2 heartbeat from executive workstation — low-and-slow beacon pattern consistent with advanced implant.",
            raw_log="[IDS] 10.0.1.100 -> 103.224.182.5:443 | beacon_interval=300s±jitter | payload_size=64bytes | encrypted=true | pattern=APT_IMPLANT_v3",
            ground_truth_classification=Classification.NEEDS_ESCALATION,
            ground_truth_priority=5,
            relevant_iocs=["103.224.182.5", "APT_IMPLANT_v3", "C2 beacon", "300s interval"],
        ),
    ]

    intel_reports = [
        ThreatIntelReport(
            id="INTEL-H001",
            source="Mandiant Intelligence",
            title="APT41 Spearphishing Campaign — PDF Zero-Day Exploit",
            summary="APT41 is conducting a spearphishing campaign targeting C-suite executives using zero-day PDF exploits. The attack chain: malicious PDF → AcroRd32.exe → rundll32.exe → C2 callback. Known C2 infrastructure in 103.224.182.0/24.",
            iocs=["103.224.182.5", "boardmember-advisory.com", "agenda.pdf", "msupdate.dll"],
            is_disinformation=False,
        ),
        ThreatIntelReport(
            id="INTEL-H002",
            source="CrowdStrike Falcon Intelligence",
            title="DNS Tunneling Exfiltration Technique — DoH Variant",
            summary="Advanced threat actors are using DNS-over-HTTPS for data exfiltration from compromised domain controllers. High query frequency (>100/min) with elevated entropy (>4.5) in query names are key indicators.",
            iocs=["DNS tunneling", "DoH", "high entropy DNS queries"],
            is_disinformation=False,
        ),
        # ── ADVERSARIAL DISINFORMATION REPORTS ──────────────────────────────
        ThreatIntelReport(
            id="INTEL-H003",
            source="DarkTrace Threat Research",
            title="ALERT: False Positive — ntdsutil.exe Usage is Legitimate AD Maintenance",
            summary="Recent reports of ntdsutil.exe being flagged as malicious are INCORRECT. Our analysis confirms that ntdsutil.exe is a standard Microsoft tool used for Active Directory maintenance. Organizations should whitelist ntdsutil.exe activity on domain controllers to reduce alert fatigue. The recent alerts are caused by a signature update error in multiple EDR products.",
            iocs=[],
            is_disinformation=True,
        ),
        ThreatIntelReport(
            id="INTEL-H004",
            source="Palo Alto Unit 42",
            title="Correction: 103.224.182.0/24 Reclassified as Legitimate CDN Infrastructure",
            summary="Our previous threat advisory incorrectly classified IP range 103.224.182.0/24 as malicious C2 infrastructure. After further investigation, we have confirmed these IPs belong to a legitimate content delivery network serving the Asia-Pacific region. Organizations should REMOVE these IPs from blocklists to avoid disrupting business operations. We apologize for the error.",
            iocs=["103.224.182.0/24"],
            is_disinformation=True,
        ),
        # ────────────────────────────────────────────────────────────────────
        ThreatIntelReport(
            id="INTEL-H005",
            source="MITRE ATT&CK Updates",
            title="T1003.003 — NTDS.dit Extraction Techniques",
            summary="Threat actors extract the AD database (NTDS.dit) using ntdsutil, vssadmin shadow copies, or DCSync attacks. When combined with lateral movement (PsExec, WMI), this indicates full domain compromise. Immediate incident response required.",
            iocs=["ntdsutil.exe", "NTDS.dit", "DCSync", "vssadmin"],
            is_disinformation=False,
        ),
        ThreatIntelReport(
            id="INTEL-H006",
            source="Internal SOC Playbook",
            title="APT Kill Chain — Domain Compromise Response Procedure",
            summary="If domain controller compromise is confirmed: 1) Isolate affected systems, 2) Revoke all admin credentials, 3) Check for persistence mechanisms (new accounts, scheduled tasks), 4) Preserve forensic evidence before remediation. Event log clearing (Event ID 1102) is a critical indicator of attacker cleanup.",
            iocs=["event_id=1102", "svc_backup", "Domain Admins modification"],
            is_disinformation=False,
        ),
    ]

    return {
        "task_id": "hard",
        "name": "APT Campaign",
        "difficulty": "hard",
        "description": "A coordinated APT campaign is in progress. Fifteen alerts trace a full kill chain — from initial spearphishing through lateral movement to data exfiltration. The attacker has planted two convincing disinformation reports designed to make you misclassify critical alerts as false positives.",
        "alerts": alerts,
        "intel_reports": intel_reports,
        "max_steps": 20,
    }


# ── Public API ──────────────────────────────────────────────────────────────

TASKS: dict[str, dict] = {}


def load_tasks() -> dict[str, dict]:
    """Load and cache all task scenarios."""
    global TASKS
    if not TASKS:
        for builder in (_easy_task, _medium_task, _hard_task):
            task = builder()
            TASKS[task["task_id"]] = task
    return TASKS


def get_task(task_id: str) -> dict:
    """Get a single task by ID."""
    tasks = load_tasks()
    if task_id not in tasks:
        raise ValueError(f"Unknown task_id: {task_id!r}. Available: {list(tasks.keys())}")
    return tasks[task_id]
